---

- name: Upgrade all APT packages
  action: apt update_cache=yes upgrade=yes
  when: not development

- name: Copying environment variable file
  template: src=environment.j2 dest=/etc/environment

- name: Install core dependencies (git)
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - git
  tags: coredeps

- include: clone.yml tags=flask