---
- name: Create docker network {{ container_network }}
  docker_network:
    name: "{{ container_network }}"
    ipam_config:
      - subnet: "{{ network_subnet }}"
        gateway: "{{ network_gateway }}"

- name: Upload source code to remote
  synchronize:
    src: "{{ playbook_dir }}/.."
    dest: "{{ src_dir }}"
  when: not ci
