---

# Add the RabbitMQ repository signing key
- apt_key: url=http://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=present

# Add RabbitMQ debian repository
- apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present

# Install RabbitMQ server
<<<<<<< HEAD
- apt: name=rabbitmq-server update_cache=yes state=present

# Set up rabbitmq vhost
- rabbitmq_vhost: name={{ rabbitmq_vhost }} state=present

# Set up RabbitMQ user
- rabbitmq_user: user={{ rabbitmq_user }}
                 password={{ rabbitmq_password }}
                 vhost={{ rabbitmq_vhost }}
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present
=======
- apt: name=rabbitmq-server update_cache=yes state=present
>>>>>>> 718ca41e21778c063c2db527ff1e59fe6646de4b
