---
- name: "Build {{ kleeweb_worker_container }} image"
  docker_image:
    build:
      path: "{{ worker_dir }}"
      pull: yes
    name: "{{ kleeweb_worker_container }}"
    source: build
    force_source: yes

- name: Get KLEE image from Docker Hub (this may take a while...) version {{ klee_version }}
  docker_image:
    name: "klee/klee{{ klee_version }}"
    source: pull
  register: klee_image

- name: Pin the above KLEE version as latest.
  docker_image:
    name: "{{ klee_image.image.Id }}"
    repository: klee/klee:latest
    force_tag: yes
    source: local
