---

- name: Get KLEE image from Docker Hub (this may take a while...)
  docker_image:
    name: klee/klee
    tag: latest
  when: not ci

- name: Install requirements for task runner
  pip: requirements={{ application_dir }}/requirements.txt virtualenv={{ worker_virtualenv }}
  become_user: worker

- name: Copy supervisor config file
  template: src=supervisor_worker.conf.j2 dest=/etc/supervisor/conf.d/worker.conf

- name: Reload supervisor configuration
  shell: supervisorctl reload
