---

# Install virtualenv
- apt: name=python-virtualenv update_cache=yes state=present

- name: Install python-dev package
  apt: name=python-dev update_cache=yes state=present

# Create worker user
- user: name=worker shell=/bin/bash

- name: Add worker to sudoers file
  lineinfile: "dest=/etc/sudoers state=present regexp='^worker' line='worker ALL=(ALL) NOPASSWD: ALL'"

# Create folder for worker files
- file: path={{ worker_working_dir }} owner=worker group=worker state=directory

# Install requirements for task runner
- pip: requirements={{ src_dir }}/python/requirements.txt virtualenv={{ worker_virtualenv }}

# Install supervisor
- apt: name=supervisor update_cache=yes state=present

- name: Start supervisor service
  service: name=supervisor state=started

# Create folder for worker log files
- file: path={{ worker_log_dir }} owner=worker group=worker state=directory

- name: Copy supervisor config file
  template: src=supervisor_worker.conf.j2 dest=/etc/supervisor/conf.d/titb_worker.conf

- name: Start flask process
  shell: supervisorctl reload