---

# Install virtualenv
- apt: name=python-virtualenv update_cache=yes state=present

# Create worker user
- user: name=worker shell=/bin/bash

# Create folder for worker files
- file: path=/worker_data/ owner=worker group=worker state=directory

# Install requirements for task runner
- pip: requirements=/titb/worker/requirements.txt virtualenv=/worker_data/env

# Copy environment file with credentials
- template: src=environment.j2 dest=/etc/environment 