---
- import_tasks: django_build.yml
  tags: ["build", "build_django"]
- import_tasks: django_deploy.yml
  tags: ["deploy_container"]
- import_tasks: nginx_build.yml
  tags: ["build", "build_nginx"]
- import_tasks: nginx_deploy.yml
  tags: ["deploy_container"]
