- name: Install nginx
  apt: pkg=nginx state=latest

- name: Remove the default site
  file: name=/etc/nginx/sites-enabled/default state=absent

- name: Remove the sites config, if exists
  file: name=/etc/nginx/sites-enabled/default state=absent

- name: Remove the default sites symlink, if exists
  file: name=/etc/nginx/sites-enabled/titb state=absent

- name: Remove existing nginx conf
  file: name=/etc/nginx/nginx.conf state=absent

- name: Configure nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: Configure nginx for the app
  template: src=sites-available_titb.conf.j2 dest=/etc/nginx/sites-available/titb group=www-data owner=www-data force=yes

- name: Enable the app
  file: src=/etc/nginx/sites-available/titb dest=/etc/nginx/sites-enabled/titb state=link

- name: Restart nginx
  action: service name=nginx state=restarted