---
- name: "Run {{ nginx_container }} container"
  docker_container:
    name: "{{ nginx_container }}"
    image: "{{ nginx_container }}"
    restart_policy: always
    networks:
      - name: "{{ container_network }}"
    ports:
      - "80:80"
    volumes:
      - /tmp:/tmp
      # Shares static files from kleeweb
      # TODO: Ideally we should have kleeweb exporting the static content
      # and then coping it into the nginx container.
      - /titb/src/static:/static
    recreate: yes
