---

# Install python dev
- apt: name=python-dev update_cache=yes state=present

- name: Install python-pip package
  apt: name=python-pip update_cache=yes state=present

# Install virtualenv
- command: pip install virtualenv

# Install supervisor
- apt: name=supervisor update_cache=yes state=present

- name: Start supervisor service
  service: name=supervisor state=started

- name: Create web user
  user: name=klee_web shell=/bin/bash

- name: Create folder for web files
  file: path={{ web_working_dir }} owner=klee_web group=klee_web state=directory

- name: Create folder for web log files
  file: path={{ web_log_dir }} owner=klee_web group=klee_web state=directory
