development: no
rabbitmq_vhost: klee
rabbitmq_host: "{{ hostvars[groups['queueservers'][0]]['ansible_' + iface].ipv4.address }}"
rabbitmq_port: 5672
rabbitmq_broker_url: "amqp://{{ rabbitmq_user }}:{{ rabbitmq_password }}@{{ rabbitmq_host }}:{{ rabbitmq_port }}/{{ rabbitmq_vhost }}"

db_host: "{{ hostvars[groups['dbservers'][0]]['ansible_' + iface].ipv4.address }}"
db_port: 5432