---
- name: Start Redis container
  docker_container:
    name: "{{ redis_container }}"
    image: redis
    restart_policy: always
    networks:
      - name: "{{ container_network }}"
    ports:
      - "6379:6379"
    recreate: yes
