- name: "Add chris-lea/redis-server PPA"
  apt_repository: repo='ppa:chris-lea/redis-server'

- name: Install Redis server
  apt: name=redis-server update_cache=yes state=present

- name: Copy redis configuration file
  template: src=redis.conf.j2 dest=/etc/redis/redis.conf

- name: Restart Redis server
  service: name=redis-server state=restarted