
---
- name: Install stunnel4 and ca-certificates
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600 state=installed
  with_items:
    - stunnel4
    - ca-certificates
  notify: stunnel - restart

- name: ssl - add certificate
  template:
    src=private.pem.j2
    dest=/etc/stunnel/private.pem
    owner=stunnel4
    group=stunnel4
    mode=0600
  notify: stunnel - restart

- name: Copy stunnel configuration
  template:
    src=stunnel-redis-server.conf.j2
    dest=/etc/stunnel/redis-server.conf
    owner=root
    group=root
    mode=0644
  notify: stunnel - restart

- name: Enable stunnel
  lineinfile:
    dest=/etc/default/stunnel4
    regexp='^ENABLED=0$'
    line='ENABLED=1'
    backrefs=yes
    state=present
  notify: stunnel - restart

- name: Enable stunnel service
  service: name=stunnel4 enabled=yes