---
- hosts: all
  remote_user: vagrant
  become: yes
  vars:
    pip_install_packages:
      - name: docker
  vars_files:
    - vars/secrets.yml
    - vars/worker-prod.yml
    - vars/common.yml
  pre_tasks:
    - name: apt-get update
      apt:
        update_cache: yes
  roles:
    - role: geerlingguy.pip
      pip_package: python3-pip
    - role: geerlingguy.docker
      when: not ci
    - common

- hosts: master
  remote_user: vagrant
  become: yes
  vars_files:
    - vars/secrets.yml
    - vars/master-prod.yml
    - vars/common.yml
  roles:
    - env_files
    - redis
    - db
    - web

- hosts: workers
  remote_user: vagrant
  become: yes
  vars_files:
    - vars/secrets.yml
    - vars/worker-prod.yml
    - vars/common.yml
  roles:
    - env_files
    - worker

- hosts: testing
  remote_user: vagrant
  become: yes
  vars_files:
    - vars/secrets.yml
    - vars/worker-prod.yml
    - vars/common.yml
  roles:
    - env_files
    - e2e-tests
