---
# Apply common configuration to all hosts
- hosts: all
  become: yes
  vars_files:
    - vars/details.yml
    - vars/secrets.yml
    - vars/production.yml
  roles:
    - angstwad.docker_ubuntu
    - common

# Configure and deploy message queue servers.
- hosts: redisservers
  become: yes
  vars_files:
    - vars/details.yml
    - vars/secrets.yml
    - vars/production.yml
  roles:
    - redis

# Configure and deploy message database servers.
- hosts: dbservers
  become: yes
  vars_files:
    - vars/details.yml
    - vars/secrets.yml
    - vars/production.yml
  roles:
    - db

# Configure and deploy the web servers.
- hosts: webservers
  become: yes
  vars_files:
    - vars/details.yml
    - vars/secrets.yml
    - vars/production.yml
  roles:
    - web

# Configure and deploy the worker nodes.
- hosts: workers
  become: yes
  vars_files:
    - vars/details.yml
    - vars/secrets.yml
    - vars/production.yml
  roles:
    - worker
