---
# Apply common configuration to all hosts
- hosts: all
  sudo: yes
  vars_files:
  - vars/secrets.yml
  - vars/production.yml
  roles:
  - common

# Configure and deploy message queue servers.
- hosts: redisservers
  vars_files:
    - vars/secrets.yml
    - vars/production.yml
  roles:
  - redis

# Configure and deploy message database servers.
- hosts: dbservers
  vars_files:
    - vars/secrets.yml
    - vars/production.yml
  roles:
  - db

# Configure and deploy the web servers.
- hosts: webservers
  vars_files:
    - vars/secrets.yml
    - vars/production.yml
  roles:
  - web

# Configure and deploy the worker nodes.
- hosts: workers
  sudo: yes
  vars_files:
  - vars/secrets.yml
  - vars/production.yml
  roles:
  - worker
  - stunnel_client
