- hosts: all
  remote_user: vagrant
  become: yes
  roles:
    - { role: angstwad.docker_ubuntu, when: not ci }
    - common
    - redis
    - db
    - web
    - worker
    - webdriver
  vars_files:
    - vars/development.yml
