---

- pip: name=flake8

- pip: name=httpie

- name: "Add chris-lea/node.js"
  apt_repository: repo='ppa:chris-lea/node.js'
  when: not ci
  tags: nodejs

- name: "Install node.js"
  apt: name=nodejs update_cache=yes
  when: not ci
  tags: nodejs

- name: "Install phantomjs"
  npm: name=phantomjs global=yes
  when: not ci

- name: "Install mocha"
  npm: name=mocha global=yes
  when: not ci

- name: "Install phantomjs"
  npm: name=phantomjs global=yes
  sudo: no
  when: ci | bool

- name: "Install mocha"
  npm: name=mocha global=yes
  sudo: no
  when: ci | bool


- name: "Install E2E test dependencies"
  npm: path={{ application_dir }}/tests
  sudo: no