---

- name: "Add chris-lea/node.js"
  apt_repository: repo='ppa:chris-lea/node.js'

- name: "Install node.js"
  apt: name=nodejs update_cache=yes

- name: "Install phantomjs"
  sudo: no
  npm: name=phantomjs global=yes

- name: "Install nightmare"
  sudo: no
  npm: name=nightmare global=yes

- name: "Install should"
  sudo: no
  npm: name=should global=yes

- name: "Install mocha"
  sudo: no
  npm: name=mocha global=yes
