---
- include: python_e2e.yml
  when: development

- name: "Build the {{ e2e_container }} container"
  docker_image:
    build:
      path: "{{ e2e_dir }}"
      pull: yes
    name: "{{ e2e_container }}"
    source: build
    force_source: yes

- name: "Start {{ e2e_container }} container"
  docker_container:
    name: "{{ e2e_container }}"
    image: "{{ e2e_container }}"
    env:
      WEBPAGE: "{{ main_webpage }}"
      ADMIN_PASSWORD: "{{ admin_password }}"
      ALERT_EMAILS: "{{ alert_emails }}"
    network_mode: "{{ container_network }}"
    detach: no

- name: Add cronjob for automated tests daily at 2pm
  cron:
    name: "Test Klee Web"
    minute: "0"
    hour: "14"
    job: "docker restart {{ e2e_container }}"
  when: not ci
